[kratos]
addr = "http://kratos-admin.kratos"

[service]
addr = "0.0.0.0"
ports.http = "8080"
ports.http_health = "1040"
ports.grpc = "5050"
ports.grpc_health="1030"

[tls]
certificate = "/certs/tls.crt"
key = "/certs/tls.key"
cert_autority = "/certs/ca.crt"
