apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- serviceaccount.yaml
- token.yaml
- deployment.yaml
- service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - config.toml
  name: iam-config
images:
- name: w6dio/iam
  newName: w6dio/iam
  newTag: v0.1.12
