apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      application: iam

namespace: w6d-bkd

patches:
- path: certmanager/deployment_tls.yaml
  target:
    kind: Deployment
    name: iam
- path: opa/sidecar.yaml
  target:
    kind: Deployment
    name: iam
    group: apps
    version: v1


resources:
- base
- opa
- certmanager

vars:
  - name: SERVICE_NAMESPACE # namespace of the service
    objref:
      kind: Service
      version: v1
      name: iam
    fieldref:
      fieldpath: metadata.namespace
  - name: SERVICE_NAME
    objref:
      kind: Service
      version: v1
      name: iam
