apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    application: iam

namespace: w6d-bkd

resources:
- ../../base
- ../../opa
- ../../certmanager

patches:
- path: sidecar.yaml
  target:
    group: apps
    kind: Deployment
    name: iam
    version: v1
- path: tls.yaml
  target:
    group: apps
    kind: Deployment
    name: iam
    version: v1

vars:
  - name: SERVICE_NAMESPACE # namespace of the service
    objref:
      kind: Service
      version: v1
      name: iam
    fieldref:
      fieldpath: metadata.namespace
  - name: SERVICE_NAME
    objref:
      kind: Service
      version: v1
      name: iam

