# The following manifests contain a self-signed issuer CR and a certificate CR.
# More document can be found at https://docs.cert-manager.io
# WARNING: Targets CertManager v1.0. Check https://cert-manager.io/docs/installation/upgrading/ for breaking changes.
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: issuer-from-ca
spec:
  ca:
    secretName: w6d-selfsigned
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: w6d-selfsigned
spec:
  commonName: w6d
  duration: 43800h0m0s
  isCA: true
  issuerRef:
    name: selfsigned
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 4096
  secretName: w6d-selfsigned