---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: iam  # this name should match the one appeared in kustomizeconfig.yaml
spec:
  # SERVICE_NAME_PLACEHOLDER and SERVICE_NAMESPACE_PLACEHOLDER will be substituted by kustomize
  commonName: $(SERVICE_NAME)
  dnsNames:
  - $(SERVICE_NAME).$(SERVICE_NAMESPACE).svc
  - $(SERVICE_NAME).$(SERVICE_NAMESPACE).svc.cluster.local
  issuerRef:
    kind: Issuer
    name: issuer-from-ca
  secretName: iam-cert # this secret will not be prefixed, since it's not managed by kustomize
