apiVersion: apps/v1
kind: Deployment
metadata:
  name: iam
spec:
  template:
    spec:
      containers:
        - name: iam
          volumeMounts:
            - mountPath: /certs
              name: cert
              readOnly: true
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: iam-cert